# NVD API Configuration
nvd.api.endpoint=https://services.nvd.nist.gov/rest/json/cves/2.0/
nvd.api.delay=4000
nvd.api.results.per.page=2000

# Database configuration
data.directory=./dependency-check-data

# Analysis configuration
analyzer.assembly.enabled=false
analyzer.msbuild.enabled=false
analyzer.nuspec.enabled=false
analyzer.nugetconf.enabled=false
analyzer.golang.enabled=true
analyzer.nodejs.enabled=true
analyzer.retirejs.enabled=true
analyzer.python.enabled=true