# Enable Swagger UI (SpringDoc OpenAPI)
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


# 🔍 Enable detailed logging for SpringDoc (OpenAPI/Swagger)
logging.level.org.springdoc=DEBUG

# 🔍 Enable detailed logging for Spring Web
logging.level.org.springframework=DEBUG
logging.level.com.fiveOps=TRACE
# 🔍 (Optional) log exceptions at root level
logging.level.root=INFO
